# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Ddzai.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x44\x64zai.proto\x12\x03\x44\x44Z\"\x1a\n\tCardArray\x12\r\n\x05\x63\x61rds\x18\x01 \x03(\x05\"H\n\nPlayerData\x12\x10\n\x08position\x18\x01 \x01(\t\x12\x12\n\nhand_cards\x18\x02 \x03(\x05\x12\x14\n\x0cplayed_cards\x18\x03 \x03(\x05\"\xac\x01\n\x10QueryNextPlayReq\x12\x13\n\x0bmy_position\x18\x01 \x01(\t\x12%\n\x0cplayer_datas\x18\x02 \x03(\x0b\x32\x0f.DDZ.PlayerData\x12\x1c\n\x14three_landlord_cards\x18\x03 \x03(\x05\x12,\n\x14\x63\x61rd_play_action_seq\x18\x04 \x03(\x0b\x32\x0e.DDZ.CardArray\x12\x10\n\x08\x62omb_num\x18\x05 \x01(\x05\"3\n\x10QueryNextPlayAck\x12\x0f\n\x07\x65rrcode\x18\x01 \x01(\x05\x12\x0e\n\x06result\x18\x02 \x03(\x05\x32G\n\x02\x41I\x12\x41\n\x0fOnQueryNextPlay\x12\x15.DDZ.QueryNextPlayReq\x1a\x15.DDZ.QueryNextPlayAck\"\x00\x62\x06proto3')



_CARDARRAY = DESCRIPTOR.message_types_by_name['CardArray']
_PLAYERDATA = DESCRIPTOR.message_types_by_name['PlayerData']
_QUERYNEXTPLAYREQ = DESCRIPTOR.message_types_by_name['QueryNextPlayReq']
_QUERYNEXTPLAYACK = DESCRIPTOR.message_types_by_name['QueryNextPlayAck']
CardArray = _reflection.GeneratedProtocolMessageType('CardArray', (_message.Message,), {
  'DESCRIPTOR' : _CARDARRAY,
  '__module__' : 'Ddzai_pb2'
  # @@protoc_insertion_point(class_scope:DDZ.CardArray)
  })
_sym_db.RegisterMessage(CardArray)

PlayerData = _reflection.GeneratedProtocolMessageType('PlayerData', (_message.Message,), {
  'DESCRIPTOR' : _PLAYERDATA,
  '__module__' : 'Ddzai_pb2'
  # @@protoc_insertion_point(class_scope:DDZ.PlayerData)
  })
_sym_db.RegisterMessage(PlayerData)

QueryNextPlayReq = _reflection.GeneratedProtocolMessageType('QueryNextPlayReq', (_message.Message,), {
  'DESCRIPTOR' : _QUERYNEXTPLAYREQ,
  '__module__' : 'Ddzai_pb2'
  # @@protoc_insertion_point(class_scope:DDZ.QueryNextPlayReq)
  })
_sym_db.RegisterMessage(QueryNextPlayReq)

QueryNextPlayAck = _reflection.GeneratedProtocolMessageType('QueryNextPlayAck', (_message.Message,), {
  'DESCRIPTOR' : _QUERYNEXTPLAYACK,
  '__module__' : 'Ddzai_pb2'
  # @@protoc_insertion_point(class_scope:DDZ.QueryNextPlayAck)
  })
_sym_db.RegisterMessage(QueryNextPlayAck)

_AI = DESCRIPTOR.services_by_name['AI']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CARDARRAY._serialized_start=20
  _CARDARRAY._serialized_end=46
  _PLAYERDATA._serialized_start=48
  _PLAYERDATA._serialized_end=120
  _QUERYNEXTPLAYREQ._serialized_start=123
  _QUERYNEXTPLAYREQ._serialized_end=295
  _QUERYNEXTPLAYACK._serialized_start=297
  _QUERYNEXTPLAYACK._serialized_end=348
  _AI._serialized_start=350
  _AI._serialized_end=421
# @@protoc_insertion_point(module_scope)
